import 'package:carport/domain/entities/reminder.dart';
import 'package:carport/domain/entities/reminder_repeat_frequency.dart';
import 'package:carport/domain/models/reminder_model.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('ReminderModel', () {
    test('round-trips each repeat frequency through map', () {
      for (final frequency in ReminderRepeatFrequency.values) {
        final model = ReminderModel(
          id: 'id-${frequency.name}',
          name: 'Oil change',
          body: 'note',
          dueAt: DateTime(2026, 3, 14, 9, 30),
          repeatFrequency: frequency,
        );

        final decoded = ReminderModel.fromMap(model.toMap());

        expect(decoded.repeatFrequency, frequency);
        expect(decoded.id, model.id);
        expect(decoded.name, model.name);
        expect(decoded.dueAt, DateTime(2026, 3, 14, 9, 30));
      }
    });

    test('null repeat frequency persists as one-time', () {
      final model = ReminderModel(
        id: 'id',
        name: 'Registration',
        body: '',
        dueAt: DateTime(2026, 3, 14, 9, 30),
        repeatFrequency: null,
      );

      final map = model.toMap();
      expect(map['repeat_frequency'], isNull);
      expect(ReminderModel.fromMap(map).repeatFrequency, isNull);
    });

    test('unknown repeat_frequency string decodes to one-time', () {
      final decoded = ReminderModel.fromMap({
        'id': 'id',
        'name': 'Legacy',
        'body': '',
        'due_at': '2026-03-14T09:30:00',
        'repeat_frequency': 'every_5000_mi',
      });

      expect(decoded.repeatFrequency, isNull);
    });

    test('toMap omits empty id (for autogenerated inserts)', () {
      final model = ReminderModel.fromEntity(
        Reminder(
          id: '',
          name: 'New',
          body: '',
          dueAt: DateTime(2026, 1, 1, 8),
          repeatFrequency: ReminderRepeatFrequency.weekly,
        ),
      );

      expect(model.toMap().containsKey('id'), isFalse);
    });
  });
}
