import 'package:carport/domain/models/service_item_model.dart';
import 'package:flutter_test/flutter_test.dart';

import '../../support/builders.dart';

void main() {
  group('ServiceItemModel', () {
    test('round-trips through toMap/fromMap', () {
      final model = ServiceItemModel(
        id: 's1',
        vehicleId: 'v1',
        title: 'Oil change',
        description: 'notes',
        date: DateTime(2026, 3, 14, 9, 30),
        mileage: 1200.5,
      );

      final decoded = ServiceItemModel.fromMap(model.toMap());

      expect(decoded.id, 's1');
      expect(decoded.vehicleId, 'v1');
      expect(decoded.title, 'Oil change');
      expect(decoded.description, 'notes');
      expect(decoded.date, DateTime(2026, 3, 14, 9, 30));
      expect(decoded.mileage, 1200.5);
    });

    test('toMap omits empty id for autogenerated inserts', () {
      final model = ServiceItemModel.fromEntity(buildServiceItem(id: ''));
      expect(model.toMap().containsKey('id'), isFalse);
    });

    test('fromMap coerces integer mileage to double', () {
      final decoded = ServiceItemModel.fromMap({
        'id': 's1',
        'vehicle_id': 'v1',
        'title': 't',
        'description': '',
        'date': '2026-01-01T00:00:00.000',
        'mileage': 1000,
      });
      expect(decoded.mileage, 1000.0);
    });

    test('fromEntity/toEntity preserve fields', () {
      final item = buildServiceItem(id: 's1', mileage: 999);
      final roundTripped = ServiceItemModel.fromEntity(item).toEntity();
      expect(roundTripped.id, 's1');
      expect(roundTripped.mileage, 999);
      expect(roundTripped.vehicleId, item.vehicleId);
    });
  });
}
