import 'package:carport/domain/models/vehicle_model.dart';
import 'package:flutter_test/flutter_test.dart';

import '../../support/builders.dart';

void main() {
  group('VehicleModel', () {
    test('round-trips through toMap/fromMap', () {
      const model = VehicleModel(
        id: 'v1',
        name: 'Civic',
        description: 'daily driver',
        maintenancePlanImage: 'plan.png',
        documentsImage: 'docs.png',
        userManualLink: 'https://user',
        maintenanceManualLink: 'https://maint',
        mileage: 12345.5,
      );

      final decoded = VehicleModel.fromMap(model.toMap());

      expect(decoded.id, 'v1');
      expect(decoded.name, 'Civic');
      expect(decoded.description, 'daily driver');
      expect(decoded.maintenancePlanImage, 'plan.png');
      expect(decoded.documentsImage, 'docs.png');
      expect(decoded.userManualLink, 'https://user');
      expect(decoded.maintenanceManualLink, 'https://maint');
      expect(decoded.mileage, 12345.5);
    });

    test('toMap omits empty id for autogenerated inserts', () {
      final model = VehicleModel.fromEntity(buildVehicle(id: ''));
      expect(model.toMap().containsKey('id'), isFalse);
    });

    test('toMap includes id when present', () {
      final model = VehicleModel.fromEntity(buildVehicle(id: 'v9'));
      expect(model.toMap()['id'], 'v9');
    });

    test('fromMap coerces integer mileage to double', () {
      final decoded = VehicleModel.fromMap({
        'id': 'v1',
        'name': 'Civic',
        'description': '',
        'maintenance_plan_image': null,
        'documents_image': null,
        'user_manual_link': null,
        'maintenance_manual_link': null,
        'mileage': 1000,
      });
      expect(decoded.mileage, 1000.0);
      expect(decoded.maintenancePlanImage, isNull);
      expect(decoded.documentsImage, isNull);
    });

    test('fromEntity/toEntity preserve fields', () {
      final vehicle = buildVehicle(
        id: 'v1',
        userManualLink: 'https://x',
        documentsImage: 'docs',
        mileage: 42,
      );
      final roundTripped = VehicleModel.fromEntity(vehicle).toEntity();
      expect(roundTripped.id, vehicle.id);
      expect(roundTripped.userManualLink, 'https://x');
      expect(roundTripped.documentsImage, 'docs');
      expect(roundTripped.mileage, 42);
    });
  });
}
